Basket/urls.py
from django.conf.urls import url
from Basket import views

urlpatterns = [
    url(r'^$', views.showBasket, name="show"),
    url(r'^addProduct/(?P<product_id>\d+)/$', views.addItemToBasket,
        name="add"),
    url(r'^deleterow/(?P<item_id>\d+)/$', views.deleteRow, name="deleteRow")
]

Product/urls.py
from django.conf.urls import url
from Product import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^shop/(?P<label>\d+)/notebooks/$',
        views.show_notebooks,
        name="notebooks"),
    ]

basket/urls.py
from django.conf.urls import url
from basket import views

urlpatterns = [
    url(r'^$', views.showBasket, name="show"),
    url(r'^addProduct/(?P<product_id>\d+)/$', views.addItemToBasket,
        name="add"),
    url(r'^deleterow/(?P<item_id>\d+)/$', views.deleteRow, name="deleteRow")
]

noteshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from noteshop import settings
from person import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^signup$', views.newUser, name='signup'),
    url(r'^create$', views.create_user, name='createuser'),
    url(r'^signin$', views.authentication, name='signin'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^', include('product.urls', namespace='Products',
                      app_name='Products')),
    url(r'^basket/', include('basket.urls', namespace='basket',
                             app_name='basket')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

product/urls.py
from django.conf.urls import url
from product import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^shop/(?P<label>\d+)/notebooks/$',
        views.show_notebooks,
        name="notebooks"),
    ]

basket/models.py
from django.db import models
from django.contrib.auth.models import User

from product.models import Good


class Basket(models.Model):
    owner = models.OneToOneField(User)


class BasketItem(models.Model):
    product = models.ForeignKey(Good)
    basket = models.ForeignKey(Basket)

    def __unicode__(self):
        return self.product.name

order/models.py
# Create your models here.

product/models.py
from django.db import models

# Create your models here.


class Good(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    picture = models.ImageField(upload_to='product_pictures')
    label = models.ForeignKey('Label')
    size = models.FloatField()
    hdd_mass = models.PositiveIntegerField()
    ram = models.PositiveIntegerField()
    processor = models.CharField(max_length=20)
    dvd = models.BooleanField()
    usb = models.PositiveIntegerField()
    videocard = models.CharField(max_length=50)
    quantity = models.PositiveIntegerField()

    def __unicode__(self):
        return self.name


class Label(models.Model):
    name = models.CharField(max_length=30)
    picture = models.ImageField(upload_to='label_pictures')

    def __unicode__(self):
        return self.name

basket/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404

# Create your views here.
from django.template import RequestContext
from basket.models import BasketItem, Basket
from product.models import Good


def addItemToBasket(request, product_id):
    item = Good.objects.get(pk=product_id)
    if request.user.is_authenticated:
        current_user = request.user
        this_basket = current_user.basket
        BasketItem.objects.create(basket=this_basket,
                                  product=item)
        return HttpResponseRedirect(reverse("basket:show"))
    else:
        return HttpResponse("Not Lol")


def showBasket(request):
    if request.user.is_authenticated:
        current_user = request.user
        this_basket = Basket.objects.get(owner=current_user)
        basket_item_list = BasketItem.objects.filter(basket=this_basket)
        cost = 0
        for item in basket_item_list:
            one_product = Good.objects.get(name=item.product)
            cost += one_product.price
        context = RequestContext(request, {
            'Items': basket_item_list,
            'price': cost
        })
        return render_to_response('basket.html', context)


def deleteRow(request, item_id):
    item = get_object_or_404(BasketItem, pk=item_id)
    if request.user.is_authenticated:
        item.delete()
        current_user = request.user
        this_basket = Basket.objects.get(owner=current_user)
        basket_item_list = BasketItem.objects.filter(basket=this_basket)
        cost = 0
        for item in basket_item_list:
            one_product = Good.objects.get(name=item.product)
            cost += one_product.price
        context = RequestContext(request, {
            'Items': basket_item_list,
            'price': cost
        })
        return HttpResponseRedirect(reverse('basket:show'), context)

order/views.py
# Create your views here.

person/views.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib import auth
from django.contrib.auth import login, logout
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect

from basket.models import Basket


def create_user(request):
    telephone = request.POST.get('telephone')
    emailu = request.POST.get('email')
    passwordu = request.POST.get('password')
    user = User.objects.create_user(username=telephone,
                                    email=emailu)
    user.set_password(passwordu)
    user.is_staff = False
    user.is_superuser = False
    user.first_name = request.POST.get('first_name')
    user.last_name = request.POST.get('last_name')
    user.save()
    current_user = user
    this_basket = Basket.objects.create(owner=current_user)
    this_basket.save()
    return HttpResponseRedirect(reverse('Products:index'))


def newUser(request):
    c = RequestContext(request, {})
    return render_to_response('signup.html', c)


@csrf_protect
def authentication(request):
        checktel = request.POST.get("telephone")
        checkpass = request.POST.get("password")
        user = auth.authenticate(username=checktel, password=checkpass)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('Products:index'))
        else:
            return HttpResponse("Not Lol")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('Products:index'))

product/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect
from product.models import Label, Good


@csrf_protect
def index(request):
    label_list = Label.objects.all()
    context = RequestContext(request, {
        'Labels': label_list
    })
    return render_to_response('index.html', context)


def show_notebooks(request, label):
    notebooks_list = Good.objects.filter(label_id=label)
    label_id = Label.objects.get(id=label)
    label_name = label_id.name
    context = RequestContext(request, {
        'Notebooks': notebooks_list,
        'Label': label_name
    })
    return render_to_response('show.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style type="text/css">
   .he {
    width: 100%;
    height:150px;
    background: #81F781;
    padding: 5px;
    padding-right: 20px;
    border: solid 1px black;
    float: left;
   }
    .user {
    width: 100%;
    height:150px;
    background: red;
    padding: 5px;
    padding-left: 40px;
    border: solid 1px black;
    float: right;
        }
    </style>
    {% load staticfiles %}
</head>
<header >
    <div class="he">
        <H1 >Онлайн магазин ноутбуков</H1>
        <h5>Алишер Санатулы</h5>
        </div>
    {% if user.is_authenticated %}
    <div class = "user">
   Привет {{ user.username }}
        <form action="{% url 'logout' %}" method='post'>
            {% csrf_token %}
            <input type="SUBMIT" VALUE="Выйти">
            </form>
        </div>
    <div>
        <form action ="{% url 'basket:show'%}" method="get">
            <input type="submit" value = "Корзина">
        </form>
    </div>
    {% else %}
    <div class = "user">
      <form action="{% url 'signin' %}" method='post'>
          {% csrf_token %}
    <label for="telephone">Логин:</label>
    <input type="text" name="telephone" value="" id="telephone">
    <label for="password">Пароль:</label>
    <input type="password" name="password" value="" id="password">


    <input type="submit" value="Зайти" />
    <input type="hidden" name="next" value="{{ next|escape }}" />

  </form>
        <form action = "{% url 'signup' %}" method="get">
            <input type = "submit" value="ЗАРЕГИСТРИРОВАТЬСЯ">
        </form>
    </div>
    {% endif%}
</header>
<body>

{% block content%}
{% endblock %}
</body>
</html>

templates/basket.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<table border="2" bordercolor="black">
    <tr bgcolor="#BDBDBD">
        <td>
            Фирма
        </td>
        <td>Модель
        </td>
        <td>Изображение
        </td>
        <td>Цена
        </td>
        <td>Тип процессора
        </td>
        <td>Оперативная память, Мб
        </td>
        <td>
            Размер,дюйм
        </td>
        <td>
            Видеоадаптер
        </td>
        <td>
            Емкость HDD, Гб
        </td>
        <td>Наличие DVD привода
        </td>
        <td>Количество USB
        </td>
        <td bgcolor = "red">

        </td>

        </tr>
{% for item in Items %}
    <tr>
        <td>
{{item.product.label}}
        </td>
        <td>
            {{item.product.name}}
        </td>
        <td>
            <img src='{{item.product.picture.url}}' width="50" height="50"/>
        </td>
        <td>
            {{item.product.price}}
        </td>
        <td>
            {{item.product.processor}}
        </td>
        <td>
            {{item.product.ram}}
        </td>
        <td>
            {{item.product.size}}
        </td>
        <td>
            {{item.product.videocard}}
        </td>
        <td>
            {{item.product.hdd_mass}}
        </td><td>
            {{item.product.dvd}}
        </td><td>
            {{item.product.usb}}
        </td>
        <td bgcolor="red">
            <form action = "{% url 'basket:deleteRow' item.id %}" method="delete">
                <input type="submit" value="X">
            </form>
        </td>


        </tr>
    {% endfor %}
</table>


<h1>Цена за все {{ price }}</h1>

</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form action="{% url 'person:signup'%}" method="post">
    {% csrf_token %}
    <label for="username">Логин</label>
    <input type ="text" name="username" id="username"/>
    <label for = "password">Пароль</label>
    <input type="password" name = "password" id="password"/>
    <input type="passwordconfirmation" name = "passwordconfirmation" value="Повторите пароль" id="passwordconfirmation"/>
    <input type="submit" value="GO FAGGS"/>
</form>
</body>1
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% for label in Labels %}

<p>
<div >
    <form action = "{% url 'Products:notebooks' label.id %}" method="get">

        <input type="submit" value="Подробнее">
        <img src = '{{label.picture.url}}' height ="150" width="250" />
    </form>

</div>
</p>
{% endfor %}

{% endblock %}

templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{Label}}</title>
</head>
<header></header>
<body>
<div>
<table border="2" bordercolor="black">
    <tr bgcolor="#BDBDBD">
        <td>
            Фирма
        </td>
        <td>Модель
        </td>
        <td>Изображение
        </td>
        <td>Цена
        </td>
        <td>Тип процессора
        </td>
        <td>Оперативная память, Мб
        </td>
        <td>
            Размер,дюйм
        </td>
        <td>
            Видеоадаптер
        </td>
        <td>
            Емкость HDD, Гб
        </td>
        <td>Наличие DVD привода
        </td>
        <td>Количество USB
        </td>
        <td bgcolor="green"></td>
        </tr>
{% for product in Notebooks %}
    <tr>
        <td>
{{Label}}
        </td>
        <td>
            {{product.name}}
        </td>
        <td>
            <img src='{{product.picture.url}}' width="50" height="50"/>
        </td>
        <td>
            {{product.price}}
        </td>
        <td>
            {{product.processor}}
        </td>
        <td>
            {{product.ram}}
        </td>
        <td>
            {{product.size}}
        </td>
        <td>
            {{product.videocard}}
        </td>
        <td>
            {{product.hdd_mass}}
        </td><td>
            {{product.dvd}}
        </td><td>
            {{product.usb}}
        </td>
        <td bgcolor="green">
        <form action="{% url 'basket:add' product.id %}" method = "post">
    {% csrf_token %}
        <input type="submit" value = "+">
</form>
</td>

        </tr>

{% endfor %}
    </table>


    </div>

</body>

</html>

templates/signup.html
<form action = "{% url 'createuser' %}" method = post>
    {% csrf_token %}
   <div><label for="tel">Ваш телефон</label>
    <input type="tel" pattern="8[0-9]{10}" name="telephone" id ='tel'/>
       </div> <div>
    <label for="emailu">Ваш email</label>
    <input type="emailu" name ="emailu" id ="emailu"/>
    </div>
    <div >
    <label for="passwordu">Пароль</label>
    <input type="password" placeholder="Password" id="passwordu" required>
    <label for="confirm_password">Повторите Пароль</label>
    <input type="password" placeholder="Confirm Password" id="confirm_password" required></div>
    <div><label for="first">Имя</label>
    <input type="text" name="first_name" id="first"/>
     </div>
    <div>
    <label for="last">Фамилия</label>

    <input type="text" name="last_name" id = "last"/></div>
    <button type="submit" class="pure-button pure-button-primary">Зарегистрироваться</button>
    <script>
    var password = document.getElementById("password"),
    confirm_password = document.getElementById("confirm_password");
    function validatePassword(){
        if(password.value != confirm_password.value) {
            confirm_password.setCustomValidity("Passwords Don't Match");
        }
        else {
            confirm_password.setCustomValidity('');
        }
    }
password.onchange = validatePassword;
confirm_password.onkeyup = validatePassword;
</script>
</form>